<?php

return [
    'lang' => 'العربية',
    'en' => 'الإنجليزية',
    'id' => 'المعرف',
    'title' => 'العنوان',
    'body' => 'المحتوى',
    'created_at' => 'تاريخ الإنشاء',
    'actions' => 'الإجراءات',
    'empty' => 'فارغ',
    'settings' => 'الإعدادات',
    'create' => 'إنشاء',
    'home' => 'الرئيسية',
    'navigation' => 'التنقل',
    'dark' => 'داكن',
    'light' => 'فاتح',
    'back' => 'عودة',
    'show' => 'عرض',
    'edit' => 'تعديل',
    'delete' => 'حذف',
    'all' => 'الكل',
    'logo' => 'الشعار',
    'login' => 'تسجيل الدخول',
    'register' => 'تسجيل',
    'employees' => 'الموظفون',
    'image' => 'الصورة',
    'name' => 'الاسم',
    'job_title' => 'المسمى الوظيفي',
    'confirm_delete' => 'تأكيد الحذف',
    'cancel' => 'إلغاء',
    'warning' => 'تحذير',
    'cover' => 'الغلاف',
    'description' => 'الوصف',
    'start_date' => 'تاريخ البدء',
    'employee' => 'الموظف',
    'date' => 'التاريخ',
    'select' => 'اختر',
    'users' => 'المستخدمون',
    'manage' => 'إدارة',
    'father_name' => 'اسم الأب',
    'mother_name' => 'اسم الأم',
];
