<?php

return [
    'lang' => 'Kurmancî',
    'en' => 'Îngilîzî',
    'id' => 'Nasname',
    'title' => 'Sernav',
    'body' => 'Naverok',
    'created_at' => 'Dîrokê afirandinê',
    'actions' => 'Çalakî',
    'empty' => 'Vala',
    'settings' => 'Mîheng',
    'create' => 'Çêkirin',
    'home' => 'Malpera sereke',
    'navigation' => 'Rêbirîn',
    'dark' => 'Tari',
    'light' => 'Ronahî',
    'back' => 'Paşve',
    'show' => 'Nîşandan',
    'edit' => 'Guherandin',
    'delete' => 'Jêbirin',
    'all' => 'Hemû',
    'logo' => 'Logoya',
    'login' => 'Têketin',
    'register' => 'Tomar kirin',
    'employees' => 'Karmend',
    'image' => 'Wêne',
    'name' => 'Nav',
    'job_title' => 'Sernavê karê',
    'confirm_delete' => 'Piştrastkirina jêbirinê',
    'cancel' => 'Bişûndekirin',
    'warning' => 'Hişyarî',
    'cover' => 'Pel',
    'description' => 'Danasîn',
    'start_date' => 'Dîrokê destpêkê',
    'employee' => 'Karmend',
    'date' => 'Dîrok',
    'select' => 'Hilbijartin',
    'users' => 'Bikarhêner',
    'manage' => 'Rêveberî',
    'father_name' => 'Navê bav',
    'mother_name' => 'Navê dayik',
];
