<?php

return [
    'lang' => 'English',
    'en' => 'english',
    'id' => 'ID',
    'title' => 'Title',
    'body' => 'Body',
    'created_at' => 'Created at',
    'actions' => 'Actions',
    'empty' => 'Empty',
    'settings' => 'Settings',
    'create' => 'Create',
    'home' => 'Home',
    'navigation' => 'Navigation',
    'dark' => 'Dark',
    'light' => 'Light',
    'back' => 'Back',
    'show' => 'Show',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'all' => 'All',
    'logo' => 'Logo',
    'login' => 'Login',
    'register' => 'Register',
    'employees' => 'Employees',
    'image' => 'Image',
    'name' => 'Name',
    'job_title' => 'Job title',
    'confirm_delete' => 'Confirm Delete',
    'cancel' => 'Cancel',
    'warning' => 'Warning',
    'cover' => 'Cover',
    'description' => 'Description',
    'start_date' => 'Start date',
    'employee' => 'Employee',
    'date' => 'Date',
    'select' => 'Select',
    'users' => 'Users',
    'manage' => 'Manage',
    'father_name' => 'Father name',
    'mother_name' => 'Mother name',
];
